export const metadata = {
  title: "Legal & Privacy | More Minutes",
  description: "Terms of service, privacy policy, and legal disclaimers",
};

"use client";
import { useRouter } from "next/navigation";

export default function LegalPage() {
  const router = useRouter();

  return (
    <main className="min-h-screen p-4 max-w-4xl mx-auto">
      <div className="mb-6">
        <button
          onClick={() => router.back()}
          className="text-accent hover:text-white mb-4 transition"
        >
          ← Back
        </button>
        <h1 className="text-3xl font-display mb-2">Legal & Privacy</h1>
        <p className="text-accent">Terms of service, privacy policy, and disclaimers</p>
      </div>

      {/* Medical Disclaimer */}
      <section className="bg-red-900/20 border border-red-800 rounded-lg p-6 mb-8">
        <h2 className="text-xl font-semibold mb-4 text-red-400">⚠️ Important Medical Disclaimer</h2>
        <div className="text-red-200 space-y-4">
          <p>
            <strong>FOR ENTERTAINMENT PURPOSES ONLY. NOT MEDICAL ADVICE.</strong>
          </p>
          <p>
            More Minutes is a recreational application designed for entertainment and awareness purposes. 
            The life expectancy predictions generated by this app are based on statistical models and 
            should NOT be interpreted as medical advice, professional health guidance, or accurate 
            predictions of your actual lifespan.
          </p>
          <p>
            Always consult with qualified healthcare professionals for medical concerns, health decisions, 
            or lifestyle changes. This app does not replace professional medical advice, diagnosis, or treatment.
          </p>
        </div>
      </section>

      {/* Privacy Policy */}
      <section className="bg-gray-900 rounded-lg p-6 mb-8">
        <h2 className="text-xl font-semibold mb-4">Privacy Policy</h2>
        <div className="prose prose-invert max-w-none space-y-4 text-sm">
          <h3 className="text-lg font-semibold">Data Collection</h3>
          <ul className="list-disc list-inside space-y-2 text-accent">
            <li>We collect minimal personal information: email, birth date, and gender</li>
            <li>All life expectancy calculations are performed locally in your browser</li>
            <li>Health data and risk factors are not transmitted to our servers</li>
            <li>Legacy Vault content is encrypted with your PIN before upload</li>
          </ul>

          <h3 className="text-lg font-semibold">Data Usage</h3>
          <ul className="list-disc list-inside space-y-2 text-accent">
            <li>Personal data is used solely to provide app functionality</li>
            <li>We do not sell, rent, or share your personal information</li>
            <li>Anonymous usage analytics help us improve the app</li>
            <li>Email is used for authentication and important service updates only</li>
          </ul>

          <h3 className="text-lg font-semibold">Data Security</h3>
          <ul className="list-disc list-inside space-y-2 text-accent">
            <li>All data is transmitted using HTTPS encryption</li>
            <li>Legacy Vault files are encrypted with AES-256-GCM</li>
            <li>Your PIN never leaves your device</li>
            <li>We implement industry-standard security practices</li>
          </ul>

          <h3 className="text-lg font-semibold">Your Rights</h3>
          <ul className="list-disc list-inside space-y-2 text-accent">
            <li>You can export all your data at any time</li>
            <li>You can delete your account and all associated data</li>
            <li>You can opt out of analytics tracking</li>
            <li>You can contact us about any privacy concerns</li>
          </ul>
        </div>
      </section>

      {/* Terms of Service */}
      <section className="bg-gray-900 rounded-lg p-6 mb-8">
        <h2 className="text-xl font-semibold mb-4">Terms of Service</h2>
        <div className="prose prose-invert max-w-none space-y-4 text-sm">
          <h3 className="text-lg font-semibold">Acceptance of Terms</h3>
          <p className="text-accent">
            By using More Minutes, you agree to these terms. If you disagree with any part of these terms, 
            please do not use our service.
          </p>

          <h3 className="text-lg font-semibold">Service Description</h3>
          <p className="text-accent">
            More Minutes provides entertainment-based life expectancy predictions and digital legacy storage. 
            The service is provided "as is" without warranties of any kind.
          </p>

          <h3 className="text-lg font-semibold">User Responsibilities</h3>
          <ul className="list-disc list-inside space-y-2 text-accent">
            <li>You must be at least 13 years old to use this service</li>
            <li>Provide accurate information for account creation</li>
            <li>Do not use the service for illegal or harmful activities</li>
            <li>Respect the intellectual property rights of others</li>
          </ul>

          <h3 className="text-lg font-semibold">Subscription Terms</h3>
          <ul className="list-disc list-inside space-y-2 text-accent">
            <li>Pro subscription is $3.99/month or $19.99/year</li>
            <li>Subscriptions auto-renew unless cancelled</li>
            <li>Cancel anytime through your account settings</li>
            <li>Refunds are handled according to platform policies</li>
          </ul>

          <h3 className="text-lg font-semibold">Limitation of Liability</h3>
          <p className="text-accent">
            More Minutes and its creators are not liable for any damages arising from use of the service. 
            The predictions are for entertainment only and should not influence important life decisions.
          </p>
        </div>
      </section>

      {/* Algorithm Information */}
      <section className="bg-gray-900 rounded-lg p-6 mb-8">
        <h2 className="text-xl font-semibold mb-4">Algorithm Transparency</h2>
        <div className="prose prose-invert max-w-none space-y-4 text-sm">
          <h3 className="text-lg font-semibold">Data Source</h3>
          <p className="text-accent">
            Life expectancy calculations are based on the U.S. Social Security Administration's 2022 Period Life Table, 
            which is public domain data representing population-level mortality statistics.
          </p>

          <h3 className="text-lg font-semibold">Methodology</h3>
          <p className="text-accent">
            We use the Gompertz mortality model with parameters calibrated to SSA data (b=0.000045, c=1.098). 
            Randomization is applied using a deterministic seed based on your profile to ensure consistent results.
          </p>

          <h3 className="text-lg font-semibold">Limitations</h3>
          <ul className="list-disc list-inside space-y-2 text-accent">
            <li>Based on population averages, not individual health</li>
            <li>Does not account for medical advances or personal circumstances</li>
            <li>Statistical models cannot predict individual outcomes</li>
            <li>Should not be used for insurance, medical, or financial planning</li>
          </ul>
        </div>
      </section>

      {/* Contact Information */}
      <section className="bg-gray-900 rounded-lg p-6">
        <h2 className="text-xl font-semibold mb-4">Contact Us</h2>
        <div className="space-y-2 text-accent">
          <p>If you have questions about these terms or our privacy practices:</p>
          <p><strong>Email:</strong> support@moreminutes.life</p>
          <p><strong>Privacy Officer:</strong> privacy@moreminutes.life</p>
          <p><strong>Last Updated:</strong> January 2025</p>
        </div>
      </section>
    </main>
  );
} 